### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by virtualritz** [olson-sean-k/theon#79]
It seems something like `theon` is needed more than ever with the number of lin. algebra crates exploding and every other crate using something else. Especially since the popular `nalgebra` becomes slow as molasses in `debug` builds.
If more crates relied on sth. like `theon` this would be a non-issue.

Speaking of which, bumping this to latest `nalgebra` is the only dependency that breaks `theon`, all other `geometry-*` features work fine against the resp. latest geometry crates.

**Comment by olson-sean-k** [comment]
> It seems something like `theon` is needed...

Yeah, I've felt this way for some time too! For intermediate library crates, I really dislike making this choice for users. That's why `theon` exists! It's a really difficult problem to solve (thoroughly) though. 😬

> Is this dead?

Only insofar that I've stretched myself a bit thin with projects. 😅  I don't consider it dead and I've been thinking about this crate recently. I've been planning on publishing [some significant changes](https://github.com/olson-sean-k/decorum/tree/mode) to [`decorum`] first before starting work on `theon` again, since it integrates with [`decorum`]. From there, I'd like to turn my sights back to [`plexus`].

That all being said, I'm not sure when any of this will actually happen at the moment.

> Speaking of which, bumping this to latest `nalgebra` is the only dependency that breaks `theon`...

That sounds about right. In my experience, `nalgebra` has had the most API churn and is the most involved crate to maintain a reverse integration with.

[`decorum`]: https://github.com/olson-sean-k/decorum
[`plexus`]: https://github.com/olson-sean-k/plexus

**Comment by olson-sean-k** [comment]
I've published [version `0.1.0`](https://crates.io/crates/theon/0.1.0), which mostly just updates the Rust Edition, MSRV, dependencies, and all integrations. This bring much better LAPACK platform support. Features now use the corresponding crate name per convention (there is no longer a "geometry" prefix). The APIs are yet unchanged, but I have plans.

**Comment by virtualritz** [comment]
Awesome! Thanks heaps. ☺️
